import {
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleDot,
  CircleSlashed,
  Download,
  Expand,
  Facebook,
  Github,
  Home,
  ImageOff,
  Info,
  Instagram,
  Laptop,
  LayoutGrid,
  LayoutList,
  LucideProps,
  Mail,
  Menu,
  Moon,
  Paintbrush2,
  Palette,
  Pipette,
  Printer,
  Search,
  Share2,
  SlidersHorizontal,
  SunMedium,
  Twitter,
  X,
  type Icon as LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  instagram: Instagram,
  github: Github,
  home: Home,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  slidersHorizontal: SlidersHorizontal,
  info: Info,
  imageOff: ImageOff,
  menu: Menu,
  layoutGrid: LayoutGrid,
  layoutList: LayoutList,
  expand: Expand,
  palette: Palette,
  pipette: Pipette,
  paintbrush2: Paintbrush2,
  circle: Circle,
  circleDot: CircleDot,
  circleSlashed: CircleSlashed,
  checkCircle: CheckCircle,
  download: Download,
  search: Search,
  arrowUpDown: ArrowUpDown,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  check: Check,
  share2: Share2,
  mail: Mail,
  facebook: Facebook,
  printer: Printer,
  x: X,
  twitter: Twitter,
};
