/**
 * NOT IN USE, COLLECTIONS GEO METADATA NOT USEFUL
 */
// https://github.com/gavinr/world-countries-centroids/releases

export const continents = [
  {
    lon: 96.086,
    lat: 52.483,
    continent: 'Asia',
  },
  {
    lon: 25,
    lat: 0,
    continent: 'Africa',
  },
  {
    lon: 96.5,
    lat: 45.5,
    continent: 'North America',
  },
  {
    lon: 54,
    lat: 15,
    continent: 'Europe',
  },
  {
    lon: -8,
    lat: -160,
    continent: 'Pacific Islands',
  },
  {
    lon: -13,
    lat: -60,
    continent: 'South America',
  },
  {
    lon: 14,
    lat: -90,
    continent: 'Central America',
  },
  {
    lon: -25,
    lat: 135,
    continent: 'Australia',
  },
  {
    lon: 30.24,
    lat: 26.605,
    continent: 'Egypt',
  },
];

export const countries = [
  {
    lon: -170.7,
    lat: -14.305,
    country: 'American Samoa',
    continent: 'Pacific Islands',
  },
  {
    lon: 166.638,
    lat: 19.302,
    country: 'United States Minor Outlying Islands',
    continent: 'Pacific Islands',
  },
  {
    lon: -159.787,
    lat: -21.222,
    country: 'Cook Islands',
    continent: 'Pacific Islands',
  },
  {
    lon: -149.4,
    lat: -17.674,
    country: 'French Polynesia',
    continent: 'Pacific Islands',
  },
  {
    lon: -169.868,
    lat: -19.052,
    country: 'Niue',
    continent: 'Pacific Islands',
  },
  {
    lon: -128.314,
    lat: -24.366,
    country: 'Pitcairn',
    continent: 'Pacific Islands',
  },
  {
    lon: -172.441,
    lat: -13.634,
    country: 'Samoa',
    continent: 'Pacific Islands',
  },
  {
    lon: -171.852,
    lat: -9.195,
    country: 'Tokelau',
    continent: 'Pacific Islands',
  },
  {
    lon: -175.204,
    lat: -21.159,
    country: 'Tonga',
    continent: 'Pacific Islands',
  },
  {
    lon: -178.127,
    lat: -14.283,
    country: 'Wallis and Futuna',
    continent: 'Pacific Islands',
  },
  {
    lon: -88.859,
    lat: 13.758,
    country: 'El Salvador',
    continent: 'Central America',
  },
  {
    lon: -90.312,
    lat: 15.82,
    country: 'Guatemala',
    continent: 'Central America',
  },
  {
    lon: -101.553,
    lat: 23.874,
    country: 'Mexico',
    continent: 'North America',
  },
  {
    lon: -98.416,
    lat: 57.55,
    country: 'Canada',
    continent: 'North America',
  },
  {
    lon: -64.532,
    lat: -35.697,
    country: 'Argentina',
    continent: 'South America',
  },
  {
    lon: -58.746,
    lat: -51.759,
    country: 'Falkland Islands',
    continent: 'South America',
  },
  {
    lon: -70.768,
    lat: -37.829,
    country: 'Chile',
    continent: 'South America',
  },
  {
    lon: -78.463,
    lat: -1.564,
    country: 'Ecuador',
    continent: 'South America',
  },
  {
    lon: -74.114,
    lat: -8.522,
    country: 'Peru',
    continent: 'South America',
  },
  {
    lon: -64.452,
    lat: -16.731,
    country: 'Bolivia',
    continent: 'South America',
  },
  {
    lon: -54.355,
    lat: -11.524,
    country: 'Brazil',
    continent: 'South America',
  },
  {
    lon: -58.389,
    lat: -23.421,
    country: 'Paraguay',
    continent: 'South America',
  },
  {
    lon: -56.019,
    lat: -32.781,
    country: 'Uruguay',
    continent: 'South America',
  },
  {
    lon: -36.775,
    lat: -54.376,
    country: 'South Georgia and South Sandwich Islands',
    continent: 'Antarctica',
  },
  {
    lon: -177.564,
    lat: -77.169,
    country: 'Antarctica',
    continent: 'Antarctica',
  },
  {
    lon: 177.981,
    lat: -17.822,
    country: 'Fiji',
    continent: 'Pacific Islands',
  },
  {
    lon: -5.717,
    lat: -15.962,
    country: 'Saint Helena',
    continent: 'Africa',
  },
  {
    lon: -63.06,
    lat: 18.222,
    country: 'Anguilla',
    continent: 'North America',
  },
  {
    lon: -61.785,
    lat: 17.071,
    country: 'Antigua and Barbuda',
    continent: 'North America',
  },
  {
    lon: -69.975,
    lat: 12.515,
    country: 'Aruba',
    continent: 'North America',
  },
  {
    lon: -78.072,
    lat: 24.721,
    country: 'Bahamas',
    continent: 'North America',
  },
  {
    lon: -59.557,
    lat: 13.183,
    country: 'Barbados',
    continent: 'North America',
  },
  {
    lon: -88.682,
    lat: 17.242,
    country: 'Belize',
    continent: 'North America',
  },
  {
    lon: -64.745,
    lat: 32.315,
    country: 'Bermuda',
    continent: 'North America',
  },
  {
    lon: -68.293,
    lat: 12.18,
    country: 'Bonaire',
    continent: 'North America',
  },
  {
    lon: -64.624,
    lat: 18.421,
    country: 'British Virgin Islands',
    continent: 'North America',
  },
  {
    lon: -81.252,
    lat: 19.311,
    country: 'Cayman Islands',
    continent: 'North America',
  },
  {
    lon: -72.644,
    lat: 4.187,
    country: 'Colombia',
    continent: 'South America',
  },
  {
    lon: -84.146,
    lat: 9.863,
    country: 'Costa Rica',
    continent: 'Central America',
  },
  {
    lon: -79.698,
    lat: 21.476,
    country: 'Cuba',
    continent: 'North America',
  },
  {
    lon: -68.969,
    lat: 12.199,
    country: 'Curacao',
    continent: 'North America',
  },
  {
    lon: -61.36,
    lat: 15.429,
    country: 'Dominica',
    continent: 'North America',
  },
  {
    lon: -70.434,
    lat: 18.779,
    country: 'Dominican Republic',
    continent: 'North America',
  },
  {
    lon: -53.322,
    lat: 3.857,
    country: 'French Guiana',
    continent: 'South America',
  },
  {
    lon: -61.679,
    lat: 12.112,
    country: 'Grenada',
    continent: 'North America',
  },
  {
    lon: -61.543,
    lat: 16.244,
    country: 'Guadeloupe',
    continent: 'North America',
  },
  {
    lon: -58.913,
    lat: 4.682,
    country: 'Guyana',
    continent: 'South America',
  },
  {
    lon: -72.892,
    lat: 18.883,
    country: 'Haiti',
    continent: 'North America',
  },
  {
    lon: -86.492,
    lat: 14.74,
    country: 'Honduras',
    continent: 'Central America',
  },
  {
    lon: -77.303,
    lat: 18.122,
    country: 'Jamaica',
    continent: 'North America',
  },
  {
    lon: -61.014,
    lat: 14.642,
    country: 'Martinique',
    continent: 'North America',
  },
  {
    lon: -62.186,
    lat: 16.735,
    country: 'Montserrat',
    continent: 'North America',
  },
  {
    lon: -85.016,
    lat: 12.893,
    country: 'Nicaragua',
    continent: 'Central America',
  },
  {
    lon: -80.144,
    lat: 8.439,
    country: 'Panama',
    continent: 'Central America',
  },
  {
    lon: -66.494,
    lat: 18.216,
    country: 'Puerto Rico',
    continent: 'North America',
  },
  {
    lon: -63.237,
    lat: 17.632,
    country: 'Saba',
    continent: 'North America',
  },
  {
    lon: -62.83,
    lat: 17.905,
    country: 'Saint Barthelemy',
    continent: 'North America',
  },
  {
    lon: -62.978,
    lat: 17.491,
    country: 'Saint Eustatius',
    continent: 'North America',
  },
  {
    lon: -62.745,
    lat: 17.314,
    country: 'Saint Kitts and Nevis',
    continent: 'North America',
  },
  {
    lon: -60.968,
    lat: 13.895,
    country: 'Saint Lucia',
    continent: 'North America',
  },
  {
    lon: -63.066,
    lat: 18.078,
    country: 'Saint Martin',
    continent: 'North America',
  },
  {
    lon: -56.324,
    lat: 46.951,
    country: 'Saint Pierre and Miquelon',
    continent: 'North America',
  },
  {
    lon: -61.193,
    lat: 13.254,
    country: 'Saint Vincent and the Grenadines',
    continent: 'North America',
  },
  {
    lon: -63.068,
    lat: 18.039,
    country: 'Sint Maarten',
    continent: 'North America',
  },
  {
    lon: -55.855,
    lat: 4.098,
    country: 'Suriname',
    continent: 'South America',
  },
  {
    lon: -61.372,
    lat: 10.415,
    country: 'Trinidad and Tobago',
    continent: 'South America',
  },
  {
    lon: -71.74,
    lat: 21.799,
    country: 'Turks and Caicos Islands',
    continent: 'North America',
  },
  {
    lon: -64.761,
    lat: 17.738,
    country: 'US Virgin Islands',
    continent: 'North America',
  },
  {
    lon: -66.364,
    lat: 7.148,
    country: 'Venezuela',
    continent: 'South America',
  },
  {
    lon: -1.693,
    lat: 12.108,
    country: 'Burkina Faso',
    continent: 'Africa',
  },
  {
    lon: -23.634,
    lat: 15.076,
    country: 'Cabo Verde',
    continent: 'Africa',
  },
  {
    lon: -5.571,
    lat: 7.536,
    country: "Côte d'Ivoire",
    continent: 'Africa',
  },
  {
    lon: -15.383,
    lat: 13.428,
    country: 'Gambia',
    continent: 'Africa',
  },
  {
    lon: -1.219,
    lat: 7.945,
    country: 'Ghana',
    continent: 'Africa',
  },
  {
    lon: -5.345,
    lat: 36.14,
    country: 'Gibraltar',
    continent: 'Europe',
  },
  {
    lon: -10.986,
    lat: 10.255,
    country: 'Guinea',
    continent: 'Africa',
  },
  {
    lon: -14.98,
    lat: 11.98,
    country: 'Guinea-Bissau',
    continent: 'Africa',
  },
  {
    lon: -9.258,
    lat: 6.52,
    country: 'Liberia',
    continent: 'Africa',
  },
  {
    lon: -4.346,
    lat: 17.168,
    country: 'Mali',
    continent: 'Africa',
  },
  {
    lon: -10.495,
    lat: 20.466,
    country: 'Mauritania',
    continent: 'Africa',
  },
  {
    lon: -8.817,
    lat: 28.687,
    country: 'Morocco',
    continent: 'Africa',
  },
  {
    lon: -7.933,
    lat: 39.675,
    country: 'Portugal',
    continent: 'Europe',
  },
  {
    lon: -14.61,
    lat: 14.228,
    country: 'Senegal',
    continent: 'Africa',
  },
  {
    lon: -11.786,
    lat: 8.561,
    country: 'Sierra Leone',
    continent: 'Africa',
  },
  {
    lon: -42.075,
    lat: 74.168,
    country: 'Greenland',
    continent: 'North America',
  },
  {
    lon: -2.576,
    lat: 49.458,
    country: 'Guernsey',
    continent: 'Europe',
  },
  {
    lon: -8.241,
    lat: 53.304,
    country: 'Ireland',
    continent: 'Europe',
  },
  {
    lon: -4.532,
    lat: 54.228,
    country: 'Isle of Man',
    continent: 'Europe',
  },
  {
    lon: -2.129,
    lat: 49.215,
    country: 'Jersey',
    continent: 'Europe',
  },
  {
    lon: -2.852,
    lat: 53.978,
    country: 'United Kingdom',
    continent: 'Europe',
  },
  {
    lon: -19.056,
    lat: 65.123,
    country: 'Iceland',
    continent: 'Europe',
  },
  {
    lon: -6.981,
    lat: 62.13,
    country: 'Faroe Islands',
    continent: 'Europe',
  },
  {
    lon: 16.036,
    lat: 78.573,
    country: 'Svalbard',
    continent: 'Europe',
  },
  {
    lon: 3.411,
    lat: -54.423,
    country: 'Bouvet Island',
    continent: 'Antarctica',
  },
  {
    lon: 170.69,
    lat: -43.827,
    country: 'New Zealand',
    continent: 'Pacific Islands',
  },
  {
    lon: 17.651,
    lat: -12.167,
    country: 'Angola',
    continent: 'Africa',
  },
  {
    lon: 23.857,
    lat: -22.236,
    country: 'Botswana',
    continent: 'Africa',
  },
  {
    lon: 29.885,
    lat: -3.261,
    country: 'Burundi',
    continent: 'Africa',
  },
  {
    lon: 43.348,
    lat: -11.658,
    country: 'Comoros',
    continent: 'Africa',
  },
  {
    lon: 14.879,
    lat: -0.729,
    country: 'Republic of the Congo',
    continent: 'Africa',
  },
  {
    lon: 23.419,
    lat: -3.338,
    country: 'Democratic Republic of the Congo',
    continent: 'Africa',
  },
  {
    lon: 11.839,
    lat: -0.628,
    country: 'Gabon',
    continent: 'Africa',
  },
  {
    lon: 37.953,
    lat: 0.689,
    country: 'Kenya',
    continent: 'Africa',
  },
  {
    lon: 28.244,
    lat: -29.601,
    country: 'Lesotho',
    continent: 'Africa',
  },
  {
    lon: 34.234,
    lat: -13.128,
    country: 'Malawi',
    continent: 'Africa',
  },
  {
    lon: 42.743,
    lat: -17.064,
    country: 'Juan De Nova Island',
    continent: 'Africa',
  },
  {
    lon: 35.208,
    lat: -17.525,
    country: 'Mozambique',
    continent: 'Africa',
  },
  {
    lon: 18.164,
    lat: -21.908,
    country: 'Namibia',
    continent: 'Africa',
  },
  {
    lon: 29.919,
    lat: -2.014,
    country: 'Rwanda',
    continent: 'Africa',
  },
  {
    lon: 6.606,
    lat: 0.227,
    country: 'Sao Tome and Principe',
    continent: 'Africa',
  },
  {
    lon: 24.752,
    lat: -28.553,
    country: 'South Africa',
    continent: 'Africa',
  },
  {
    lon: 31.51,
    lat: -26.562,
    country: 'Eswatini',
    continent: 'Africa',
  },
  {
    lon: 34.818,
    lat: -6.355,
    country: 'Tanzania',
    continent: 'Africa',
  },
  {
    lon: 27.755,
    lat: -13.162,
    country: 'Zambia',
    continent: 'Africa',
  },
  {
    lon: 29.717,
    lat: -18.927,
    country: 'Zimbabwe',
    continent: 'Africa',
  },
  {
    lon: 72.435,
    lat: -7.323,
    country: 'British Indian Ocean Territory',
    continent: 'Pacific Islands',
  },
  {
    lon: 69.546,
    lat: -49.263,
    country: 'French Southern Territories',
    continent: 'Antarctica',
  },
  {
    lon: 73.492,
    lat: -53.084,
    country: 'Heard Island and McDonald Islands',
    continent: 'Antarctica',
  },
  {
    lon: 46.684,
    lat: -19.041,
    country: 'Madagascar',
    continent: 'Africa',
  },
  {
    lon: 57.564,
    lat: -20.281,
    country: 'Mauritius',
    continent: 'Africa',
  },
  {
    lon: 45.128,
    lat: -12.824,
    country: 'Mayotte',
    continent: 'Africa',
  },
  {
    lon: 47.29,
    lat: -11.566,
    country: 'Glorioso Islands',
    continent: 'Africa',
  },
  {
    lon: 55.543,
    lat: -21.119,
    country: 'Réunion',
    continent: 'Africa',
  },
  {
    lon: 55.472,
    lat: -4.66,
    country: 'Seychelles',
    continent: 'Africa',
  },
  {
    lon: 2.655,
    lat: 28.35,
    country: 'Algeria',
    continent: 'Africa',
  },
  {
    lon: 2.305,
    lat: 9.503,
    country: 'Benin',
    continent: 'Africa',
  },
  {
    lon: 12.948,
    lat: 6.294,
    country: 'Cameroon',
    continent: 'Africa',
  },
  {
    lon: 20.52,
    lat: 6.331,
    country: 'Central African Republic',
    continent: 'Africa',
  },
  {
    lon: 18.427,
    lat: 15.283,
    country: 'Chad',
    continent: 'Africa',
  },
  {
    lon: 10.425,
    lat: 1.595,
    country: 'Equatorial Guinea',
    continent: 'Africa',
  },
  {
    lon: -157.39,
    lat: 1.867,
    country: 'Kiribati',
    continent: 'Pacific Islands',
  },
  {
    lon: 17.911,
    lat: 27.202,
    country: 'Libya',
    continent: 'Africa',
  },
  {
    lon: 14.441,
    lat: 35.89,
    country: 'Malta',
    continent: 'Europe',
  },
  {
    lon: 8.868,
    lat: 17.081,
    country: 'Niger',
    continent: 'Africa',
  },
  {
    lon: 8.147,
    lat: 9.61,
    country: 'Nigeria',
    continent: 'Africa',
  },
  {
    lon: 0.899,
    lat: 8.66,
    country: 'Togo',
    continent: 'Africa',
  },
  {
    lon: 9.655,
    lat: 34.086,
    country: 'Tunisia',
    continent: 'Africa',
  },
  {
    lon: 33.375,
    lat: 35.117,
    country: 'Cyprus',
    continent: 'Asia',
  },
  {
    lon: 42.613,
    lat: 11.75,
    country: 'Djibouti',
    continent: 'Africa',
  },
  {
    lon: 30.24,
    lat: 26.605,
    country: 'Egypt',
    continent: 'Egypt',
  },
  {
    lon: 39.267,
    lat: 15.005,
    country: 'Eritrea',
    continent: 'Africa',
  },
  {
    lon: 39.914,
    lat: 8.729,
    country: 'Ethiopia',
    continent: 'Africa',
  },
  {
    lon: 23.11,
    lat: 39.42,
    country: 'Greece',
    continent: 'Europe',
  },
  {
    lon: 43.832,
    lat: 33.105,
    country: 'Iraq',
    continent: 'Asia',
  },
  {
    lon: 35.027,
    lat: 31.513,
    country: 'Israel',
    continent: 'Asia',
  },
  {
    lon: 36.957,
    lat: 31.387,
    country: 'Jordan',
    continent: 'Asia',
  },
  {
    lon: 35.896,
    lat: 33.911,
    country: 'Lebanon',
    continent: 'Asia',
  },
  {
    lon: 35.242,
    lat: 31.93,
    country: 'Palestinian Territory',
    continent: 'Asia',
  },
  {
    lon: 30.385,
    lat: 7.657,
    country: 'South Sudan',
    continent: 'Africa',
  },
  {
    lon: 29.951,
    lat: 15.67,
    country: 'Sudan',
    continent: 'Africa',
  },
  {
    lon: 38.511,
    lat: 35.097,
    country: 'Syria',
    continent: 'Asia',
  },
  {
    lon: 35.568,
    lat: 38.932,
    country: 'Turkey',
    continent: 'Asia',
  },
  {
    lon: 32.343,
    lat: 1.282,
    country: 'Uganda',
    continent: 'Africa',
  },
  {
    lon: 1.58,
    lat: 42.548,
    country: 'Andorra',
    continent: 'Europe',
  },
  {
    lon: -96.331,
    lat: 38.82,
    country: 'United States',
    continent: 'North America',
  },
  {
    lon: 2.194,
    lat: 46.642,
    country: 'France',
    continent: 'Europe',
  },
  {
    lon: 9.547,
    lat: 47.146,
    country: 'Liechtenstein',
    continent: 'Europe',
  },
  {
    lon: 7.412,
    lat: 43.747,
    country: 'Monaco',
    continent: 'Europe',
  },
  {
    lon: 8.286,
    lat: 46.736,
    country: 'Switzerland',
    continent: 'Europe',
  },
  {
    lon: 4.675,
    lat: 50.618,
    country: 'Belgium',
    continent: 'Europe',
  },
  {
    lon: 10.426,
    lat: 51.083,
    country: 'Germany',
    continent: 'Europe',
  },
  {
    lon: 6.103,
    lat: 49.775,
    country: 'Luxembourg',
    continent: 'Europe',
  },
  {
    lon: 5.554,
    lat: 52.134,
    country: 'Netherlands',
    continent: 'Europe',
  },
  {
    lon: 20.061,
    lat: 41.141,
    country: 'Albania',
    continent: 'Europe',
  },
  {
    lon: 13.797,
    lat: 47.631,
    country: 'Austria',
    continent: 'Europe',
  },
  {
    lon: 17.834,
    lat: 44.144,
    country: 'Bosnia and Herzegovina',
    continent: 'Europe',
  },
  {
    lon: 16.625,
    lat: 44.911,
    country: 'Croatia',
    continent: 'Europe',
  },
  {
    lon: 15.383,
    lat: 49.749,
    country: 'Czech Republic',
    continent: 'Europe',
  },
  {
    lon: 9.378,
    lat: 56.001,
    country: 'Denmark',
    continent: 'Europe',
  },
  {
    lon: 19.396,
    lat: 47.225,
    country: 'Hungary',
    continent: 'Europe',
  },
  {
    lon: 12.763,
    lat: 42.982,
    country: 'Italy',
    continent: 'Europe',
  },
  {
    lon: 19.295,
    lat: 42.736,
    country: 'Montenegro',
    continent: 'Europe',
  },
  {
    lon: 19.435,
    lat: 52.068,
    country: 'Poland',
    continent: 'Europe',
  },
  {
    lon: 12.461,
    lat: 43.942,
    country: 'San Marino',
    continent: 'Europe',
  },
  {
    lon: 20.856,
    lat: 44.026,
    country: 'Serbia',
    continent: 'Europe',
  },
  {
    lon: 19.581,
    lat: 48.698,
    country: 'Slovakia',
    continent: 'Europe',
  },
  {
    lon: 14.89,
    lat: 46.137,
    country: 'Slovenia',
    continent: 'Europe',
  },
  {
    lon: 21.709,
    lat: 41.594,
    country: 'North Macedonia',
    continent: 'Europe',
  },
  {
    lon: 12.451,
    lat: 41.904,
    country: 'Vatican City',
    continent: 'Europe',
  },
  {
    lon: 16.67,
    lat: 64.977,
    country: 'Norway',
    continent: 'Europe',
  },
  {
    lon: 17.062,
    lat: 62.734,
    country: 'Sweden',
    continent: 'Europe',
  },
  {
    lon: 27.964,
    lat: 53.467,
    country: 'Belarus',
    continent: 'Europe',
  },
  {
    lon: 25.251,
    lat: 42.82,
    country: 'Bulgaria',
    continent: 'Europe',
  },
  {
    lon: 25.916,
    lat: 58.648,
    country: 'Estonia',
    continent: 'Europe',
  },
  {
    lon: 25.657,
    lat: 65.015,
    country: 'Finland',
    continent: 'Europe',
  },
  {
    lon: 43.378,
    lat: 42.179,
    country: 'Georgia',
    continent: 'Asia',
  },
  {
    lon: 24.693,
    lat: 56.813,
    country: 'Latvia',
    continent: 'Europe',
  },
  {
    lon: 23.946,
    lat: 55.294,
    country: 'Lithuania',
    continent: 'Europe',
  },
  {
    lon: 28.391,
    lat: 47.072,
    country: 'Moldova',
    continent: 'Europe',
  },
  {
    lon: 25.094,
    lat: 45.824,
    country: 'Romania',
    continent: 'Europe',
  },
  {
    lon: 31.273,
    lat: 48.657,
    country: 'Ukraine',
    continent: 'Europe',
  },
  {
    lon: 66.592,
    lat: 34.134,
    country: 'Afghanistan',
    continent: 'Asia',
  },
  {
    lon: 50.54,
    lat: 26.047,
    country: 'Bahrain',
    continent: 'Asia',
  },
  {
    lon: 81.173,
    lat: 23.586,
    country: 'India',
    continent: 'Asia',
  },
  {
    lon: 54.237,
    lat: 32.906,
    country: 'Iran',
    continent: 'Asia',
  },
  {
    lon: 47.563,
    lat: 29.281,
    country: 'Kuwait',
    continent: 'Asia',
  },
  {
    lon: 73.1,
    lat: -0.606,
    country: 'Maldives',
    continent: 'Asia',
  },
  {
    lon: 84.133,
    lat: 28.3,
    country: 'Nepal',
    continent: 'Asia',
  },
  {
    lon: 55.841,
    lat: 20.724,
    country: 'Oman',
    continent: 'Asia',
  },
  {
    lon: 69.088,
    lat: 30.116,
    country: 'Pakistan',
    continent: 'Asia',
  },
  {
    lon: 51.197,
    lat: 25.318,
    country: 'Qatar',
    continent: 'Asia',
  },
  {
    lon: 44.6,
    lat: 24.136,
    country: 'Saudi Arabia',
    continent: 'Asia',
  },
  {
    lon: 45.4,
    lat: 6.524,
    country: 'Somalia',
    continent: 'Africa',
  },
  {
    lon: 80.669,
    lat: 7.696,
    country: 'Sri Lanka',
    continent: 'Asia',
  },
  {
    lon: 70.942,
    lat: 38.569,
    country: 'Tajikistan',
    continent: 'Asia',
  },
  {
    lon: 58.457,
    lat: 39.06,
    country: 'Turkmenistan',
    continent: 'Asia',
  },
  {
    lon: 54.279,
    lat: 24.182,
    country: 'United Arab Emirates',
    continent: 'Asia',
  },
  {
    lon: 47.468,
    lat: 16.001,
    country: 'Yemen',
    continent: 'Asia',
  },
  {
    lon: 45.054,
    lat: 40.178,
    country: 'Armenia',
    continent: 'Asia',
  },
  {
    lon: 48.634,
    lat: 40.392,
    country: 'Azerbaijan',
    continent: 'Asia',
  },
  {
    lon: 66.375,
    lat: 47.641,
    country: 'Kazakhstan',
    continent: 'Asia',
  },
  {
    lon: 74.175,
    lat: 41.356,
    country: 'Kyrgyzstan',
    continent: 'Asia',
  },
  {
    lon: 63.854,
    lat: 41.487,
    country: 'Uzbekistan',
    continent: 'Asia',
  },
  {
    lon: 105.702,
    lat: -10.446,
    country: 'Christmas Island',
    continent: 'Pacific Islands',
  },
  {
    lon: 96.836,
    lat: -12.171,
    country: 'Cocos Islands',
    continent: 'Pacific Islands',
  },
  {
    lon: 113.965,
    lat: 0.155,
    country: 'Indonesia',
    continent: 'Asia',
  },
  {
    lon: 125.95,
    lat: -8.809,
    country: 'Timor-Leste',
    continent: 'Asia',
  },
  {
    lon: 134.022,
    lat: -25.697,
    country: 'Australia',
    continent: 'Australia',
  },
  {
    lon: 166.929,
    lat: -0.522,
    country: 'Nauru',
    continent: 'Pacific Islands',
  },
  {
    lon: 165.507,
    lat: -21.33,
    country: 'New Caledonia',
    continent: 'Pacific Islands',
  },
  {
    lon: 167.952,
    lat: -29.037,
    country: 'Norfolk Island',
    continent: 'Australia',
  },
  {
    lon: 144.834,
    lat: -7.156,
    country: 'Papua New Guinea',
    continent: 'Pacific Islands',
  },
  {
    lon: 160.164,
    lat: -9.613,
    country: 'Solomon Islands',
    continent: 'Pacific Islands',
  },
  {
    lon: 179.217,
    lat: -8.514,
    country: 'Tuvalu',
    continent: 'Pacific Islands',
  },
  {
    lon: 166.849,
    lat: -15.189,
    country: 'Vanuatu',
    continent: 'Pacific Islands',
  },
  {
    lon: 105.039,
    lat: 12.699,
    country: 'Cambodia',
    continent: 'Asia',
  },
  {
    lon: 103.763,
    lat: 18.117,
    country: 'Laos',
    continent: 'Asia',
  },
  {
    lon: 114.633,
    lat: 3.671,
    country: 'Malaysia',
    continent: 'Asia',
  },
  {
    lon: 97.088,
    lat: 19.901,
    country: 'Myanmar',
    continent: 'Asia',
  },
  {
    lon: 103.81,
    lat: 1.352,
    country: 'Singapore',
    continent: 'Asia',
  },
  {
    lon: 101.086,
    lat: 13.662,
    country: 'Thailand',
    continent: 'Asia',
  },
  {
    lon: 105.913,
    lat: 16.517,
    country: 'Vietnam',
    continent: 'Asia',
  },
  {
    lon: 90.432,
    lat: 23.673,
    country: 'Bangladesh',
    continent: 'Asia',
  },
  {
    lon: 90.467,
    lat: 27.421,
    country: 'Bhutan',
    continent: 'Asia',
  },
  {
    lon: 104.691,
    lat: 38.073,
    country: 'China',
    continent: 'Asia',
  },
  {
    lon: 114.643,
    lat: 4.543,
    country: 'Brunei',
    continent: 'Asia',
  },
  {
    lon: 121.822,
    lat: 15.586,
    country: 'Philippines',
    continent: 'Asia',
  },
  {
    lon: 127.762,
    lat: 36.402,
    country: 'South Korea',
    continent: 'Asia',
  },
  {
    lon: 103.398,
    lat: 47.086,
    country: 'Mongolia',
    continent: 'Asia',
  },
  {
    lon: 127.337,
    lat: 40.191,
    country: 'North Korea',
    continent: 'Asia',
  },
  {
    lon: 144.78,
    lat: 13.445,
    country: 'Guam',
    continent: 'Pacific Islands',
  },
  {
    lon: 137.469,
    lat: 36.767,
    country: 'Japan',
    continent: 'Asia',
  },
  {
    lon: 168.72,
    lat: 7.307,
    country: 'Marshall Islands',
    continent: 'Pacific Islands',
  },
  {
    lon: 158.229,
    lat: 6.878,
    country: 'Micronesia',
    continent: 'Pacific Islands',
  },
  {
    lon: 145.741,
    lat: 15.178,
    country: 'Northern Mariana Islands',
    continent: 'Pacific Islands',
  },
  {
    lon: 134.579,
    lat: 7.534,
    country: 'Palau',
    continent: 'Pacific Islands',
  },
  {
    lon: 98.67,
    lat: 59.039,
    country: 'Russian Federation',
    continent: 'Europe',
  },
  {
    lon: -3.651,
    lat: 40.365,
    country: 'Spain',
    continent: 'Europe',
  },
  {
    lon: -16.537,
    lat: 28.297,
    country: 'Canarias',
    continent: 'Africa',
  },
];
